# Generated by Django 4.1.2 on 2022-10-17 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40, null=True)),
                ('email', models.CharField(max_length=50, null=True, unique=True)),
                ('phone', models.CharField(max_length=10, null=True)),
                ('date', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
    ]
