# Generated by Django 4.1.2 on 2022-10-17 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta_website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40, null=True)),
                ('category', models.CharField(choices=[('tshirt', 'tshirt'), ('bottle', 'bottle'), ('magic_mug', 'magic_mug'), ('keychain', 'keychain'), ('dictionary_item', 'dictionary_item')], max_length=50, null=True)),
                ('color', models.CharField(max_length=50, null=True)),
                ('description', models.CharField(max_length=250, null=True)),
                ('price', models.FloatField(null=True)),
                ('image_url', models.CharField(max_length=600)),
                ('size', models.CharField(max_length=3, null=True)),
                ('date_created', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='date',
            new_name='date_created',
        ),
    ]
