# Generated by Django 4.1.2 on 2022-10-17 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta_website', '0002_order_product_rename_date_customer_date_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
        migrations.AddField(
            model_name='order',
            name='size',
            field=models.CharField(choices=[('s', 's'), ('m', 'm'), ('l', 'l'), ('xl', 'xl')], max_length=3, null=True),
        ),
    ]
